### ISSUE TITLE
Put operation without preceding Get operation fails after the first attempt

### ISSUE THREAD

**Issue by komamitsu** [scalar-labs/scalardb#689]
**Describe the bug**
I'm playing with https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md#store--retrieve-data.  I might be missing something, but I noticed Put operation without preceding Get operation for the same target record fails after the first test finishes successfully. It works when I try to fetch the target record using `TransactionCrudOperable.get()` before Put operation.

**To Reproduce**

1. Prepare config file
```
# The JDBC URL
scalar.db.contact_points=jdbc:postgresql://localhost:5432/
scalar.db.username=scalardb
scalar.db.password=xxxxxx
scalar.db.storage=jdbc
scalar.db.consensus_commit.isolation_level=SERIALIZABLE
```
2. Setup table schema using schema loader with https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md#set-up-database-schema
3. Add the following code to  https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md#store--retrieve-data
```java
public class ElectronicMoney implements Closeable {
  :
    public void set(String id, int amount) throws TransactionException {
        DistributedTransaction tx = manager.start();

        try {
            Put put =
                    Put.newBuilder()
                            .namespace(NAMESPACE)
                            .table(TABLENAME)
                            .partitionKey(Key.ofText(ID, id))
                            .intValue(BALANCE, amount)
                            .build();
            tx.put(put);

            tx.commit();
        } catch (Exception e) {
            tx.abort();
            throw e;
        }
    }

    public static void main(String[] args) throws IOException, TransactionException {
        try (ElectronicMoney emoney = new ElectronicMoney()) {
            emoney.set("komamitsu", 42);
        }
    }
}
```
4. Execute `ElectronicMoney.main()`. The first execution would finish successfully.
5. Execute `ElectronicMoney.main()` again.
6. See error

**Expected behavior**
The test code should finish successfully without any error even it's 2nd execution or later.

**Error message**
```
Exception in thread "main" com.scalar.db.exception.transaction.CommitConflictException: preparing record exists
	at com.scalar.db.transaction.consensuscommit.CommitHandler.prepare(CommitHandler.java:63)
	at com.scalar.db.transaction.consensuscommit.CommitHandler.commit(CommitHandler.java:42)
	at com.scalar.db.transaction.consensuscommit.ConsensusCommit.commit(ConsensusCommit.java:121)
	at ElectronicMoney.set(ElectronicMoney.java:47)
	at ElectronicMoney.main(ElectronicMoney.java:56)
Caused by: com.scalar.db.exception.storage.NoMutationException: no mutation was applied
Caused by: com.scalar.db.exception.storage.NoMutationException: no mutation was applied

	at com.scalar.db.storage.jdbc.JdbcDatabase.put(JdbcDatabase.java:111)
	at com.scalar.db.storage.jdbc.JdbcDatabase.mutate(JdbcDatabase.java:151)
	at com.scalar.db.transaction.consensuscommit.CommitHandler.lambda$prepareRecords$0(CommitHandler.java:81)
	at com.scalar.db.transaction.consensuscommit.ParallelExecutor.executeTasks(ParallelExecutor.java:97)
	at com.scalar.db.transaction.consensuscommit.ParallelExecutor.prepare(ParallelExecutor.java:52)
	at com.scalar.db.transaction.consensuscommit.CommitHandler.prepareRecords(CommitHandler.java:83)
	at com.scalar.db.transaction.consensuscommit.CommitHandler.prepare(CommitHandler.java:52)
	... 4 more
```

**PostgreSQL records**
```
scalardb=> select * from coordinator.state ;
                tx_id                 | tx_state | tx_created_at
--------------------------------------+----------+---------------
 c9679069-e489-4b60-8d39-f799fbdba8d0 |        3 | 1662294830783
 0ef1552e-2928-4e58-a33c-915340f26701 |        4 | 1662294975106
(2 rows)

scalardb=> select * from emoney.account ;
    id     | balance |                tx_id                 | tx_state | tx_version | tx_prepared_at | tx_committed_at | before_tx_id | before_tx_state | before_tx_version | before_tx_prepared_at | before_tx_committed_at | before_balance
-----------+---------+--------------------------------------+----------+------------+----------------+-----------------+--------------+-----------------+-------------------+-----------------------+------------------------+----------------
 komamitsu |      42 | c9679069-e489-4b60-8d39-f799fbdba8d0 |        3 |          1 |  1662294830519 |   1662294830787 |              |                 |                   |                       |                        |
(1 row)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Java 8
 - Version: Scalar DB 3.6.0

BTW, this issue template doesn't seem to really fit this project (e.g. browser) ?

**Comment by brfrn169** [comment]
@komamitsu Thank you for your question!

Scalar DB doesn't allow blind writes except when the records to write don't exist. That's why you faced the error at the 2nd execution. If you want to write already existing records, you need to read (Get or Scan) them and then write (Put or Delete) them.

**Comment by komamitsu** [comment]
@brfrn169 Thanks for the answer! Glad to hear it's an expected behavior. I'm closing this issue.

BTW, I looked over the document, but couldn't find this restriction. It would be great if the restriction is written somewhere.

**Comment by brfrn169** [comment]
> BTW, I looked over the document, but couldn't find this restriction. It would be great if the restriction is written somewhere.

@komamitsu That's true. Thank you for the feedback!
