### ISSUE TITLE
Add missing table name to this exception message `StorageRuntimeException: no table information found`

### ISSUE THREAD

**Issue by Torch3333** [scalar-labs/scalardb#86]
**Is your feature request related to a problem? Please describe.**
Let's state that this is a program executing a Put request targeting a Cassandra table named `FooTable` using the **transaction** mode.

When Scalar DB fails to execute the `Put` because `FooTable` was not created in Cassandra, the stack trace will look like this.
```
no table information found
com.scalar.db.exception.storage.StorageRuntimeException: no table information found
	at com.scalar.db.storage.cassandra.ClusterManager.getMetadata(ClusterManager.java:83)
	at com.scalar.db.storage.cassandra.Cassandra.getTableMetadata(Cassandra.java:185)
	at com.scalar.db.storage.cassandra.Cassandra.get(Cassandra.java:79)
	at com.scalar.db.transaction.consensuscommit.RollbackMutationComposer.getLatestResult(RollbackMutationComposer.java:145)
	at com.scalar.db.transaction.consensuscommit.RollbackMutationComposer.add(RollbackMutationComposer.java:60)
	at com.scalar.db.transaction.consensuscommit.Snapshot.lambda$to$0(Snapshot.java:126)
	at java.util.concurrent.ConcurrentHashMap$EntrySetView.forEach(ConcurrentHashMap.java:4795)
	at com.scalar.db.transaction.consensuscommit.Snapshot.to(Snapshot.java:122)
	at com.scalar.db.transaction.consensuscommit.RecoveryHandler.rollback(RecoveryHandler.java:58)
	at com.scalar.db.transaction.consensuscommit.CommitHandler.commit(CommitHandler.java:44)
	at com.scalar.db.transaction.consensuscommit.ConsensusCommit.commit(ConsensusCommit.java:121)
        at com.scalar.ist.api.ScalarDBTest.put(ScalarDBTest.java:71)
...
```
Since the stracktrace is originating from the faulty user code, I tend to think that `FooTable` is missing which is correct in that case.

But, in the case the `FooTable` was created but the  `coordinator.state` table is missing. The exception will look like this :
```
no table information found
com.scalar.db.exception.storage.StorageRuntimeException: no table information found
	at com.scalar.db.storage.cassandra.ClusterManager.getMetadata(ClusterManager.java:83)
	at com.scalar.db.storage.cassandra.Cassandra.getTableMetadata(Cassandra.java:185)
	at com.scalar.db.storage.cassandra.Cassandra.checkIfPrimaryKeyExists(Cassandra.java:191)
	at com.scalar.db.storage.cassandra.Cassandra.put(Cassandra.java:107)
	at com.scalar.db.transaction.consensuscommit.Coordinator.put(Coordinator.java:101)
	at com.scalar.db.transaction.consensuscommit.Coordinator.putState(Coordinator.java:49)
	at com.scalar.db.transaction.consensuscommit.CommitHandler.commitState(CommitHandler.java:114)
	at com.scalar.db.transaction.consensuscommit.CommitHandler.commit(CommitHandler.java:62)
	at com.scalar.db.transaction.consensuscommit.ConsensusCommit.commit(ConsensusCommit.java:121)
	at com.scalar.ist.api.ScalarDBTest.put(ScalarDBTest.java:71)
...
```
The exception message is identical to the missing `FooTable` but the stacktrace partly differs. Though, it is not obvious that the `coordinator.state` table is missing and not the `FooTable`.

It happened that I spent some time trying to understand what was wrong because I was convinced wrongly that Scalar DB could not find the `FooTable` for some reason even though the coordinator table was the one missing. 
I guess new Scalar DB users who are still not fully aware that the coordinator table is required may be quite confused as well.

**Describe the solution you'd like**
The exception message below could be updated to include the missing table keyspace and name 
```
com.scalar.db.exception.storage.StorageRuntimeException: no table information found
```

**Comment by brfrn169** [comment]
As the following PR has resolved this issue, closing it. 
https://github.com/scalar-labs/scalardb/pull/178

After this fix, IllegalArgumentException will be thrown when a specified table is missing, and the message will include the missing table namespace and name.

Thank you for reporting it! @Torch3333
